### PR TITLE
Add imagej.deleteOtherVersions property

### PR DESCRIPTION
**Pull request by stelfrich**
Add a property to define overwriting behavior in more fine-grained manner (when compared to `delete.other.versions`):
- `imagej.deleteOtherVersions=never`: do not overwrite files in destination
- `imagej.deleteOtherVersions=always`: do always overwrite existing files in destination
- `imagej.deleteOtherVersions=older`: overwrite older versions (i.e. keep newer ones)

This deprecates the old `delete.other.versions` and will show a warning whenever it is explicitly set. If it is not set, the expected behavior is kept.

### CODE REVIEW

**Comment by stelfrich** [comment]
Taking inspiration from #10, we could include `imagej.deleteOtherVersions=incompatible` to delete other versions if it is incompatible according to SemVer, i.e. a different major version.

**Comment by stelfrich** [comment]
> we could include `imagej.deleteOtherVersions=incompatible` to delete

After a short discussion with @ctrueden, we have decided to not implement that as a separate option but give a warning if `imagej.deleteOtherVersions=older` and you are overwriting with an incompatible version.

**Comment by stelfrich** [comment]
Thanks to a lot of help from @ctrueden (seriously: thanks for https://github.com/scijava/scijava-common/commit/82ce585ca0a676d12ee1f612664766cb1ac1cd4d!) this is good to merge once *scijava-common:2.66.0* is released.

**Comment by ehrenfeu** [comment]
This should also be reflected in the corresponding section of the [Developing ImageJ in Eclipse][1] page, right? If you agree, I can simply update the wiki...

[1]: http://imagej.net/Developing_ImageJ_in_Eclipse#Option_2:_Install_dependencies

**Comment by stelfrich** [comment]
Good catch @ehrenfeu. Feel free to update the wiki - I would appreciate it :+1:

**Comment by ehrenfeu** [comment]
Done :heavy_check_mark:

**Pull request merged**
